---
# Deploy sonarqube
- name: Pull sonarqube docker image
  docker_image:
    name: "{{ SONARQUBE_DOCKER_IMG }}:{{ SONARQUBE_DOCKER_TAG }}"
    source: pull

- name: sonarqube Container started
  docker_container:
    name: sonarqube
    state: started
    image: "{{ SONARQUBE_DOCKER_IMG }}:{{ SONARQUBE_DOCKER_TAG }}"
    links:
     - "postgres:postgres"
    ports:
      - "9000:9000"
      - "9092:9092"
    env:
      SONAR_JDBC_USERNAME: "sonarqube"
      SONAR_JDBC_PASSWORD: "{{ CUSTOM_PASSWORD }}"
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ulimits: nofile:131072:131072
