---
# tasks file for docker
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when:
    - CONF_MIRROR
    - ansible_distribution == "Amazon"

# - name: Uninstall old versions of docker
#   package:
#     name: "{{ AMZ_DOCKER_OLD_VERSIONS }}"
#     state: absent
#   when:
#     - CONF_MIRROR
#     - ansible_distribution == "Amazon"

# - name: Add repository
#   get_url:
#     url: https://download.docker.com/linux/centos/docker-ce.repo
#     dest: /etc/yum.repos.d/docker-ce.repo
#     mode: '0644'
#   when:
#     - CONF_MIRROR
#     - ansible_distribution == "Amazon"

# - name: Add repository
#   yum_repository:
#     name: docker
#     description: Docker repo
#     baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#   when:
#     - CONF_MIRROR
#     - ansible_distribution == "Amazon"

- name: Update repo lists
  yum:
    list: updates
    update_cache: true
  when:
    - CONF_MIRROR
    - ansible_distribution == "Amazon"

- name: Install Docker Engine
  package:
    name: "{{ DOCKER_PACKAGES }}"
    state: present
  when:
    - ansible_distribution == "Amazon"

- name: Enable Docker Engine
  systemd:
    name: docker
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == "Amazon"
